# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    sudo npm install --force --production
  displayName: 'Install Local Node Libraries'

- script: |
    npm install -g gatsby-cli
  displayName: 'Install Gatsby CLI'

- script: |
    gatsby build
  displayName: 'Generating Static Files'
